### ISSUE TITLE
Allow build variables for transformations

### ISSUE THREAD

**Issue by wertzui** [sergeyzwezdin/magic-chunks#1]
I need to transform a connection string based on the build variable Build.SourceBranch.
It would be nice if your tool supported passing in build variables in VSTS, so it is possible to create transformations based on these variables.

**Comment by sergeyzwezdin** [comment]
@wertzui if you use it as VSTS extension, feel free to use any available variable, for example transofrmation file could be:

```json
{
   "path/to/transform": "Branch is $(Build.SourceBranch)"
}
```

This is what you're asking for?

**Comment by wertzui** [comment]
Didn't know, it was already working, thanks :)
