### ISSUE TITLE
The ':' character, hexadecimal value 0x3A, cannot be included in a name

### ISSUE THREAD

**Issue by dachibox** [sergeyzwezdin/magic-chunks#12]
Hi, I'm using cake an trying to changes the Package.appmanifest file of Universal Windows Platform apps.

It works fine, until I'm trying to change an property that have namespaces **(uap:VisualElements)**
 `Package/Applications/Application/uap:VisualElements/@DisplayName`

the error message is like:
_The ':' character, hexadecimal value 0x3A, cannot be included in a name_

Thank's and greetings!

**Comment by sergeyzwezdin** [comment]
Fixed. Will be available in `1.2`.

**Comment by dachibox** [comment]
great! thanks! :)

**Comment by sergeyzwezdin** [comment]
Build `1.2` has been shipped.
