### ISSUE TITLE
Using magic-chunks with a netcoreapp1.0 project

### ISSUE THREAD

**Issue by DBCI** [sergeyzwezdin/magic-chunks#18]
Hello,

As I essentially want to transform appsettings.json during the MSBuild phase, I tried adding magic-chunks to my project but the following error message pops up:

> Package MagicChunks 1.2.0.58 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package MagicChunks 1.2.0.58 supports: net45 (.NETFramework,Version=v4.5)

Any ideas? Any intent of support netcoreapps ?

Thanks,
DB

**Comment by sergeyzwezdin** [comment]
Hi,
Correct. Current implementation based on .NET 4.5, .NET Core.
Migration to .NET is planned, but I can't provide exact ETA for the moment.
I'll update here once it happens.

**Comment by sergeyzwezdin** [comment]
Magic Chunks migrated to .NET Standard for the moment.
Will be released as part of 1.3.0.

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
