### ISSUE TITLE
Cannot see 'Config transformation' task when using TFS 2015 Update 2

### ISSUE THREAD

**Issue by rrreynolds** [sergeyzwezdin/magic-chunks#2]
Does the extension support TFS 2015 Update 2?

I do not see the extension listed under the "_Add tasks_" dialog when attempting to adding a build step. I have confirmed that the extension is installed on the server and is installed into the team project collection I'm trying to use it in.

**Comment by sergeyzwezdin** [comment]
Already reported to Microsoft guys about this issue. Will investigate by myself as well.

**Comment by sergeyzwezdin** [comment]
Good, some results after some invetigations.

I've created fresh VM and installed TFS 2015 there. Next, I tried to install extension into TFS local gallery and installed it for project collection. TFS displayed that it's installed sucessfully, but it didn't appear at "Add build step" dialog.

I took some pause and returned back to continue investigation when noticed the build task appeared at "Add build step" dialog. So it seems TFS needed some time to install the extension before you can use it.

<img width="583" alt="build" src="https://cloud.githubusercontent.com/assets/800755/16170025/35c2d350-355d-11e6-893b-021014d9f953.PNG">

Just in case I've decreased agent version for extension (as on-premise TFS have lower agent version than VS Online).

So could you try to install latest version and check whether it will appear after some time?

/cc @rrreynolds @viperguynaz

**Comment by rrreynolds** [comment]
@sergeyzwezdin I installed the latest version as of today (1.0.0) and the task showed up immediately after installation. I am running TFS 2015 Update 2

**Comment by sergeyzwezdin** [comment]
@rrreynolds well, I have no idea how TFS processing it internally. From time to time it displaying immediatelly, and from time to time - not. Same bahavior for other extensions, so I guess it's normal for TFS.

**Comment by kp2015** [comment]
So this is still not loading.  I've disabled / reenabled  and have waited since yesterday when I opened issue #5 which was a duplicate of this one.  But still not showing in the list.  

any thoughts?

**Comment by rrreynolds** [comment]
@kp2015 can you verify that you have actually installed the extension into the collection are trying to use it in? I would suggest that you completely remove the extension from the "Manage Extensions" screen (http://buildserver:8080/tfs/_gallery/manage) and then reinstall the latest version. That fixed it for me for this particular extension.

**Comment by sergeyzwezdin** [comment]
@kp2015 @rrreynolds correct. You have to install into your local TFS gallery first, and then install it for project collection. Did you try this?

**Comment by Vitus** [comment]
test comment

**Comment by sanyogitaranade** [comment]
We know this issue and we are actively working to resolve it. It is a cache related problem and hence is intermittent and difficult to track down. So far, we have seen the best solution is to try to uninstall and reinstall the extension as rrreynolds correctly mentioned.
