### ISSUE TITLE
Help: how to change an "add" and how to delete 

### ISSUE THREAD

**Issue by lboening** [sergeyzwezdin/magic-chunks#20]
I have an app.config file. It has many "add" entries in the "appSettings" section.

Using your tool, it is easy to add a key with a particular value.

But how do I target a particular "add", such as the fourth one in the list? 

Example:
`
<add key="MaxConcurrentAutoVueControls" value="3" />
`

If I add, I then have two keys, one with the proper setting. The fourth one on the list is still in the appSettings set with unchanged values.

Is it possible to delete a particular key with your tool? 

I know how to do it using other techniques.

**Comment by markjose** [comment]
Maybe a bit late to the party here but you can address individual <add /> nodes by using the key.
`{
  "configuration/appInfo/add[@key='SomeKey']/@value": "SomeValue",
  "configuration/appInfo/add[@key='SomeKey']/@value": "$(SomeBuildOrReleaseVariable)",
}`

**Comment by sergeyzwezdin** [comment]
@lboening Could you please explain a bit detailed this case:

> If I add, I then have two keys, one with the proper setting

It would be useful to have piece of you config file as well as your transformations.
If you have duplication of `MaxConcurrentAutoVueControls` key, it won't be correct behavior and should be treated as a bug.

**Comment by sergeyzwezdin** [comment]
Also, as @markjose mentioned before, you can address specific key by `add[@key=...]` syntax.

**Comment by sergeyzwezdin** [comment]
Another part of you request is deleting nodes. Because of this, I mark it as new feature request and will try to take a look what I can do here.

**Comment by sergeyzwezdin** [comment]
I've added syntax to remove nodes.
In upcoming 1.3.0 version it will be possible to do something like this:

```json
{
  "#configuration/appInfo/add[@key='SomeKey']/@value": ""
}
```

Please note, that `#` at the start of transformation key means that node will be deleted.

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.

**Comment by bondort** [comment]
Hey @sergeyzwezdin how do I add the "clear" tag mentioned by you above?
I tried adding `"configuration/connectionStrings/clear": ""` but it created a `<clear></clear>` tag which is incorrect.
Thanks
