### ISSUE TITLE
Specify the correct node

### ISSUE THREAD

**Issue by JeroenHo** [sergeyzwezdin/magic-chunks#21]
Hi,

In the Xml I want to modify there are several nodes with the same name and I want to change a child node of one of the nodes.
Example
```
<info>
	<param>
		<option>AA</option>
	</param>
	<param>
		<option>BB</option>
		<argument>CC</argument>
	</param>
</info>
```

The value of the argument node should be modified depending on the type of build. But if I use "info/param/argument", it results in a new argument in the first param node.

Any way to fix this...Maybe with "info/param[2]/argument" to specify the correct node? Just like in XPath

Many thanks

**Comment by Noah-Silvera** [comment]
I'm experiencing a similar problem with being unable to target multiple nodes with the same element name in a list

**Comment by maldworth** [comment]
+1

I'd like this feature

**Comment by sergeyzwezdin** [comment]
Thank you for your feedback.
Fixed in upcoming `1.3.0` version.
Now you can do that this way: `info/param[1]/argument`.
Please note that index for XML-node is zero-based.

**Comment by Noah-Silvera** [comment]
Thanks @sergeyzwezdin !

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
