### ISSUE TITLE
Access to the path '<source_file_to_transform>' is denied

### ISSUE THREAD

**Issue by adailsonfilho** [sergeyzwezdin/magic-chunks#24]
Hi!

First of all, thank you for making this open source! I'm using it within TFS 2015 (update 4). Just after "get sources" I've tried to transform my web.config and got this:

> ##[error]Exception calling "Transform" with "4" argument(s): "Access to the path '<Path_to_my_build_agent_workspce>\<myproject>\web.config' is denied."

I thought it was an "IsReadOnly" issue, so I cleared it before using PowerShell and still with this error. Any ideas what should be the problem? Thank you in advance!

**Comment by adailsonfilho** [comment]
Sorry guys, my bad. My "IsReadOnly Cleaner" script wasn't doing its job correctly.

**Comment by sergeyzwezdin** [comment]
@adailsonfilho Thank you for getting us know!
