### ISSUE TITLE
TFS Release Integration - Secret Variable Values?

### ISSUE THREAD

**Issue by lewisveale** [sergeyzwezdin/magic-chunks#25]
Is there a way of handling the "secret" variable values when using the TFS Release task?
For instance, we have a number of passwords in our environment variables, which have been made secret to avoid exposing them to prying eyes.
![capture](https://user-images.githubusercontent.com/21249679/29082793-9531a746-7c5e-11e7-94e6-9f312862156b.PNG)
I would like the task to be able to decrypt these and put them in the transformed config files.
Thanks!

**Comment by sergeyzwezdin** [comment]
@lewisveale Just use it as regular variable:

```json
{
    "configuration/password": "$(AppPoolPassword)"
}
```
