### ISSUE TITLE
Incompatible with Cake version > v.0.21.1

### ISSUE THREAD

**Issue by anderaus** [sergeyzwezdin/magic-chunks#27]
Using the latest version of Cake released today ([v.0.22.0](https://github.com/cake-build/cake/releases/tag/v0.22.0)) and referencing MagicChunks in a cake script outputs this error:

`
Error: The assembly 'MagicChunks.Cake, Version=1.2.0.58, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.16.2).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
`

**Comment by sergeyzwezdin** [comment]
@anderaus Thank you for letting me know. I plan to update magic-chunks soon.

**Comment by Lakritzator** [comment]
Can you tell us when the update might be there, I currently have a failing build and I don't know how to solve it with the many dependencies I have. This seems to be the last which needs an update.

**Comment by gep13** [comment]
@Lakritzator you should be able to skip this verification check, using the information in the error message which is printed above.

**Comment by gep13** [comment]
@sergeyzwezdin thanks for getting this updated, looking forward to the next release.

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.

**Comment by gep13** [comment]
@sergeyzwezdin this is great news! This is my goto library for updating files nowadays 😄

**Comment by sergeyzwezdin** [comment]
@gep13 👍
