### ISSUE TITLE
Using deprecated version of YamlDotNet deserializer configurator

### ISSUE THREAD

**Issue by anderaus** [sergeyzwezdin/magic-chunks#29]
Building the current version gives this deprecation warning:

`'Deserializer.Deserializer(IObjectFactory, INamingConvention, bool, YamlAttributeOverrides)' is obsolete: 
'Please use DeserializerBuilder to customize the Deserializer. This constructor will be removed in future releases.'`

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
