### ISSUE TITLE
Question about XML rootpath

### ISSUE THREAD

**Issue by swavans** [sergeyzwezdin/magic-chunks#30]
Hi,
So I don't have much experience with this tool but maybe you could help me?

I think it has something todo with this part of the wiki but I do not quite get what you mean.

"Please note that you can have single root node for XML. So if the first element in transformation path does not match name of root element in source file you will get error:  "

What I have is a file called POM.XML (see Below for refference) and I want to replace "inputSpec" in a vsts build task. This looks like this: 
![image](https://user-images.githubusercontent.com/17268986/31622376-8b87532a-b29c-11e7-830a-014567cc9aaf.png)

So when I run it I get this exception: 
 Exception calling "Transform" with "4" argument(s): "Root element name does not match path.

What am I doing wrong?

```
<project xmlns=some configuration stuff>

    <build>
        <plugins>
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.2.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec></inputSpec>
                            <language>csharp</language>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by sergeyzwezdin** [comment]
@swavans you should point full path to your node. The first element in path should match root node name.
In your sample `project` is root node, so your path should start with it:

```json
{
   "project/plugins/plugin/executions/execution/configuration/inputSpec": "...",
   ...
}
```
