### ISSUE TITLE
Release to nuget

### ISSUE THREAD

**Issue by karlatkinson** [sergeyzwezdin/magic-chunks#31]
#27 has been closed but the update has not yet been released to nuget.
Is anything blocking this? Had to pin quite a few packages to older versions to support this.

Thanks

**Comment by sergeyzwezdin** [comment]
There is no reason to open new issue just for a question. You can always ask at #27 for example :-)
Yes, there are number of issues with #17, which is planned for this release as well.
I'm working on it now, once it will be done, I'll publish it to nuget.

**Comment by karlatkinson** [comment]
That's a good point! Thanks for the update.

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
