### ISSUE TITLE
Preserve XML header

### ISSUE THREAD

**Issue by pascalberger** [sergeyzwezdin/magic-chunks#32]
If I have an existing XML document like this, and running some transformations the XML header in the first line will be removed.

```
<?xml version="1.0" encoding="utf-8"?>
<foo>
</foo>
```

Is there a way to have the XML header preserved?

**Comment by pascalberger** [comment]
It seems like a `XmlDocument.ToString()` is called [here](https://github.com/sergeyzwezdin/magic-chunks/blob/master/src/MagicChunks/Documents/XmlDocument.cs#L209) which will remove existing XML header.

**Comment by sergeyzwezdin** [comment]
Thank you for your contribution!

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
