### ISSUE TITLE
How to select processing instructions?

### ISSUE THREAD

**Issue by robertvanGilst** [sergeyzwezdin/magic-chunks#35]
I have got a Wix Install file.
```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <?define ProductName="My product for ArcGIS 10.2"?>
  <?define ProductVersion="1.3.0.0" ?>
</Wix>
```

Where I would like to match the define with the ProductName and update the attribute value for that one. How should I select?
I tried with:

> Wix/?define/@ProductName

and

> Wix/processing-instruction(define)/@ProductName

But both fail in the update process.

**Comment by sergeyzwezdin** [comment]
@robertvanGilst Is this fragment valid XML document?

**Comment by robertvanGilst** [comment]
Yes, processing instructions are part of the [XML Standard](https://www.w3.org/TR/xml/#sec-pi)

I maybe should have included:
`<?xml version="1.0" encoding="UTF-8"?>`

It contains only the tags I am interested to update, the rest of file I have left out.

**Comment by sergeyzwezdin** [comment]
Indeed, ok. It is not supported for the moment.  I'll take a look

**Comment by robertvanGilst** [comment]
Thank you.

**Comment by sergeyzwezdin** [comment]
Thank you for your report.
I just fixed the issue.
You can address elements by index:
```
Wix/?define[0]/@ProductName
```
Or by attribute name:
```
Wix/?define[@ProductName = 'My product for ArcGIS 10.2']/@ProductName
```

Will be released soon as part of 1.3.0.

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.

**Comment by robertvanGilst** [comment]
Hi Sergey,

Thank you very much for the quick response and fix.


Med venlig hilsen

Robert van Gilst
Senior Business Solution Consultant

Powel Danmark A/S, Gråbrødregade 9, 1. sal, DK-6000 Kolding, DENMARK
Mobil: +45 61 20 42 34
Email: Robert.van.Gilst@powel.dk<mailto:Robert.van.Gilst@powel.dk>

[cid:image002.jpg@01D204F0.B2F6DA30]<http://www.powel.no/>[cid:image003.jpg@01D204F0.B2F6DA30]<https://www.facebook.com/pages/Powel/350917775700>[cid:image004.jpg@01D204F0.B2F6DA30]<http://www.linkedin.com/company/powel-as>
