### ISSUE TITLE
Problem with colon in key name

### ISSUE THREAD

**Issue by aslabicki** [sergeyzwezdin/magic-chunks#37]
I have problem with magic-chunks in cake build. When I try to replace value of this **configuration/appSettings/add[@key='ida:issuer']/@value**, then I get error 
_("The ''' character, hexadecimal value 0x27, cannot be included in a name.")_, but this **configuration/appSettings/add[@key='issuer']/@value** works fine. It look colon makes difference in this case.

**Comment by sergeyzwezdin** [comment]
Thank for your report. I'll take a look.

**Comment by sergeyzwezdin** [comment]
The issue was fixed by @iKaew as part of #34

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
