### ISSUE TITLE
VisualStudio Extension Update

### ISSUE THREAD

**Issue by xaberx** [sergeyzwezdin/magic-chunks#38]
Hi, I use magic chunks for our deploys and saw a post that you could delete nodes using the # symbol as of version 1.3.0 . The Visual Studio Extension is still running 1.2.0, when do you think you can push the latest version to the marketplace? I really like this tool and it helps make our agile process much more streamlined. src: https://github.com/sergeyzwezdin/magic-chunks/issues/20

**Comment by sergeyzwezdin** [comment]
Thank you for your kind of word. I will publish in near time.

**Comment by sergeyzwezdin** [comment]
Latest fixes were released to Nuget and VS Marketplace.
