### ISSUE TITLE
You have a possible copy cat

### ISSUE THREAD

**Issue by RazorSPoint** [sergeyzwezdin/magic-chunks#39]
Hi,

I just noticed that you have a copycat. He didn't even care to substantially add stuff to your code or adding anything. The help, screenshots and everything are the same.

Have a look here:
https://github.com/BTolliday/Transformer
https://marketplace.visualstudio.com/items?itemName=Dreamlax.Transformer

That's a real ripoff. He is not event mentioning you!

**Comment by sergeyzwezdin** [comment]
Thank you very much for the link.
I disappointed with his behavoir.

Posted [here](https://github.com/BTolliday/Transformer/issues/5) about it, hope @BTolliday will respect key OSS values and will remove his clone.

Let's see.

**Comment by RazorSPoint** [comment]
No problem. But maybe you also want to report the duplicate in the VSTS marketplace. He seemed to have removed the repository, but not the extension.
