### ISSUE TITLE
No agent could be found with the following capabilities: DotNetFramework, Xamarin.iOS, sh

### ISSUE THREAD

**Issue by rgiampietro** [sergeyzwezdin/magic-chunks#43]
![msbuild_error](https://user-images.githubusercontent.com/32174363/34169744-9cf846ce-e4a5-11e7-8720-e0d5d561e6ac.jpeg)
When I add a Task using the Config Transformation in MSBuild I get the following message when I try to Queue the build:

No agent could be found with the following capabilities: DotNetFramework, Xamarin.iOS, sh.

Is there some additional setup that needs to be done after installing from the marketplace to get around this issue?

Thanks!

**Comment by sergeyzwezdin** [comment]
Which OS and build agent version do you use?

**Comment by rgiampietro** [comment]
We're running TFS 2018 on premise.
- Two Mac mini's have a build agent with version 2.126.0 installed.
- Looks like the official build number of TFS is Version 16.122.27102.1

Thanks for the help and excellent extension !

**Comment by sergeyzwezdin** [comment]
It doesn't support Mac build agents yet. Will be introduced soon.
Use #7 to track progress.

**Comment by nukec** [comment]
@sergeyzwezdin great plugin. I have no issue on win machine, but if i want to build ios app same error appears.
