### ISSUE TITLE
Nuget packages after 1.2.0 + fail to work with cake.build on VSTO

### ISSUE THREAD

**Issue by mit-jamie-clayton** [sergeyzwezdin/magic-chunks#48]
I'm not sure if this is really a bug in the Magic-Chunks nuget package building process or how cakebuild.net uses nuget references in it's codebase. I'm posting to help others.

Using magic chunks within a cake.build script via the Microsoft VSTO online CI plugin causes the nuget package to fail with cake.build CI tool. https://cakebuild.net/ when the process tries to use the magic chunks nuget packages greater than 1.2.0.x

This applies to cakebuild 0.21.1, 0.24.0 works as expected with Magic Chunks.  Looks like I had checked a file into source control that fixed the edition of cakebuild.

## Steps to reproduce 
Add the following to a cake.build script 
#addin nuget:https://www.nuget.org/api/v2?package=MagicChunks 

> Error: Failed to install addin 'MagicChunks'.
> --
> System.Exception: Unexpected exit code 1 returned from tool Cake.exe
> PowerShell script completed with 1 errors.

## Steps to resolve
Change the addin reference to 
#addin nuget:https://www.nuget.org/api/v2?package=MagicChunks&version=1.2.0.58

**Comment by sergeyzwezdin** [comment]
@mit-jamie-clayton Hello. Thaks for posting. It's related #42. Please use this issue to watch the progress.
