### ISSUE TITLE
Issue w/ Extension Showing up in on premise add tasks

### ISSUE THREAD

**Issue by kp2015** [sergeyzwezdin/magic-chunks#5]
Installed the extension fine this morning.  Enabled on one of my collections.  Says successful.  I got into a build and or create new build, go to utility and am not seeing it showing. What are some potential reasons why? and where can i look for any 'error' messages or something
 that could be hindering it from showing. Attached a screenshot .

![image](https://cloud.githubusercontent.com/assets/15907768/16197472/2eeb592a-36d0-11e6-8040-b48febaaf15e.png)

Thanks!

**Comment by sergeyzwezdin** [comment]
Wait some time :-) For some reasons TFS displays it with delay.
I explanined it at #2

**Comment by outofbounder** [comment]
I am seeing this with https://github.com/sergeyzwezdin/magic-chunks/issues/9.  After "some time" the plugin requires being installed to the collection again (it uninstalls itself)

**Comment by sergeyzwezdin** [comment]
@outofbounder I beleive it's TFS's issue, not extension's. I'm not sure how extension code could affect this behavior. So I think it's better to ping MS team how things is going

// @sanyogitaranade

**Comment by outofbounder** [comment]
Thanks.  Yea I am also on premise with update 2 FYI.
