### ISSUE TITLE
Update Cake addin to Cake 0.26.0

### ISSUE THREAD

**Issue by pascalberger** [sergeyzwezdin/magic-chunks#58]
Cake 0.26.0 introduced breaking changes in the API. The Cake addin should be built against Cake 0.26.0 to be compatible with current version

**Comment by gep13** [comment]
@sergeyzwezdin I just wanted to follow up with this issue.  Are you in a position to update the Cake Addin for MagicChunks?  It would be great to have this updated.  Thanks!

**Comment by futuralogic** [comment]
Any ETA on this being addressed?

**Comment by pascalberger** [comment]
@sergeyzwezdin Would it be an option for you to split the core Magic Chunks and the Cake addin into separate repositories, with the Cake addin being part of the [Cake-Contrib](https://github.com/cake-contrib) organization and more people having write access, so that the community can help to keep the Cake addin up to date?

**Comment by JenasysDesign** [comment]
I've updated the VSTS _build.ps1 code to fix the automated build for the https://github.com/sergeyzwezdin/magic-chunks/pull/65 to help improve compatibility with the newer editions of Cake.build.
