### ISSUE TITLE
Possible to have recursive search in the config transform source path?

### ISSUE THREAD

**Issue by rrreynolds** [sergeyzwezdin/magic-chunks#6]
Would it be possible to add an option to perform a recursive search for the source path? I have not been able to get this to work. I have tried the standard formats such as "**\web.config", etc.
There is another task available in the [marketplace](https://marketplace.visualstudio.com/items?itemName=TotalALM.totalalm-tokenization) which supports this option but I prefer your XML/Xpath searching since it requires no changes to the config files in the code repository.

**Comment by sergeyzwezdin** [comment]
Yep, at weekends I will take a look how it's implemented and will try to add this feature here as well.

**Comment by Christoffleroux** [comment]
Would realy like to have this feature available , it helps when using MSDeploy packages

**Comment by sergeyzwezdin** [comment]
Fixed and will be available as part of `1.2`.

Now you can point `*.json` as source file for example. Also you you want to recursively search files in directory there is new option `Recursive search`.

**Comment by sergeyzwezdin** [comment]
Build `1.2` has been shipped.
