### ISSUE TITLE
Cake.Core version 0.26.0 compliance issue

### ISSUE THREAD

**Issue by akgulebubekir** [sergeyzwezdin/magic-chunks#69]
**Here is the error message:**

```
Error: The assembly 'MagicChunks.Cake, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.23.0).
This assembly must reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

**Comment by JenasysDesign** [comment]
https://github.com/sergeyzwezdin/magic-chunks/pull/65 includes a fix to this issue. Just waiting on @sergeyzwezdin to review that PR.

**Comment by sunilshahi** [comment]
Any update on this? We have been waiting on this.

**Comment by cpriem** [comment]
Hey,

My team is receiving this error as well, is there an update to when a fix will be released?

Thanks!

**Comment by jstrubeATlicensysDOTcom** [comment]
I'm getting a slightly different error this when running cake:

dotnet : Error: The assembly 'MagicChunks.Cake, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' 
Publish.ps1:5 char:1
+ dotnet cake build.cake
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: The asse...KeyToken=null' :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
How can this be resolved?

Cheers.

**Comment by pascalberger** [comment]
https://github.com/sergeyzwezdin/magic-chunks/pull/65 has been merged. Next version of Magic Chunks will work with current version of Cake.
